### PR TITLE
Add option to specify a source attribute on a per version basis

### PR DESCRIPTION
**Pull request by Sauraus**

### CODE REVIEW

**Comment by heathsnow** [comment]
I've removed Hound integration for this cookbook.  It should hound us no more.

**Comment by sneal** [comment]
@Sauraus There's a merge conflict, I think from your other PR.

@Sauraus @heathsnow I've been thinking about how we can improve the usability and maintainability of the cookbook. I think it would be better if we drop backwards compatibility.

1. Remove `node['visualstudio']['source']` attribute usage and move towards having a download URL for each version/edition.
2. Remove `node['visualstudio'][version][edition]['filename']` attribute
3. Add `node['visualstudio'][version][edition]['install_url']` attribute and default it to the publicly available ISOs.

```
node['visualstudio']['2013']['community']['source'] = 
'http://download.microsoft.com/download/A/A/D/AAD1AA11-FF9A-4B3C-8601-054E89260B78/vs2013.5_ce_enu.iso'

node['visualstudio']['2013']['ultimate']['source'] = 
'http://download.microsoft.com/download/A/A/D/AAD1AA11-FF9A-4B3C-8601-054E89260B78/vs2013.5_ult_enu.iso'
```

**Comment by Sauraus** [comment]
Cleaned up the pull request.

**Comment by sneal** [comment]
@Sauraus Build failed with a Rubocop error about complexity.

**Comment by Sauraus** [comment]
What does that error even mean? :)

**Comment by sneal** [comment]
Replaced by https://github.com/windowschefcookbooks/visualstudio/pull/3

**Pull request closed without merging**
