### PR TITLE
Updated cookbook to handle multiple versions of Visual Studio.

### PR DESCRIPTION
**Pull request by dthagard**
* Added setup for Visual Studio 2013.

### CODE REVIEW

**Comment by sneal** [comment]
This looks really good, thanks!

**Comment by sneal** [comment]
Unfortunately this breaks 2012 support since both the 2012 and 2013 attribute files use the same attribute keys, the 2013 attribute values clobber the 2012 attribute values (since the 2013 attribute file is included last).

**Comment by yeungs** [comment]
I agree. I had ended up make a copy of the recipe to vs-2012 and vs-2013 so I can install Visual Studio in Chef run on one single system. :(

**Comment by iankendrick** [comment]
I took another stab at this here, converting install.rb and update.rb into LWRPs:

https://github.com/iankendrick/visualstudio/tree/lwrp_conversion

My use case was installing VS2010 and VS2012, including both as resources in a wrapper recipe.  I'll need to add VS2013 eventually.

Let me know if there's any interest and I'll clean it up for a PR. It doesn't seem to have any breaking changes, but it should probably have a new recipe to work only as a resource provider.

**Comment by sneal** [comment]
Closing for #24 which will support VS 2010 -> 2015

**Pull request closed without merging**
