### PR TITLE
Add VS2015 Enterprise and Support for adding Product Keys during installation

### LINKED ISSUE #38: Ability to install with ProductKey
There doesn't appear to be a way to install with a product key.

This would be really handy for use on build servers and the like where no user interaction will be happening.  

I'm happy to investigate and submit a PR if nobody else has already solved this issue.

### PR DESCRIPTION
**Pull request by ShawInnes**
- Provides the ability to specify a product key for each version/edition of Visual Studio
- Added Visual Studio 2015 Enterprise configuration

fixes #38

### CODE REVIEW

**Comment by ShawInnes** [comment]
Note: I was having issues installing VS2015 via chef (through test-kitchen) where I receive a failure code of 1603 if I don't install KB2999226 first.  I don't know if anyone else is having this behaviour and whether it should be an explicitly forced pre-requisite, or whether calling it out in the README is sufficient.

**Comment by sneal** [comment]
This looks really good, thanks!

**Comment by ShawInnes** [comment]
Excellent.

I was a bit confused about whether I should close the PR or not... sorry
about that :)

On 19 November 2015 at 05:06, Shawn Neal <notifications@github.com> wrote:

> This looks really good, thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/daptiv/visualstudio/pull/39#issuecomment-157824550>.
>



--

**Comment by sneal** [comment]
Closing, changes are in #42

**Pull request closed without merging**
