### PR TITLE
Ability to customize items in the AdminDeployment.xml

### PR DESCRIPTION
**Pull request by zacht-ontsys**
AdminDeployment.xml is used by VS versions >2010 for adding features in an unattended install. This is created with a `template` instead of `cookbook_file`.

### CODE REVIEW

**Comment by stoiky** [comment]
Nice one sir. Looking for it to land.

**Comment by sneal** [comment]
@zacht-ontsys Nice work. This looks good to me except for the addition of depending on the dotnetframework cookbook.

**Comment by zacht-ontsys** [comment]
@sneal Added another commit removing that, thanks!

**Comment by sneal** [comment]
Closing, pulled PR into [new repo location](https://github.com/windowschefcookbooks/visualstudio). Will be released soon.

**Pull request closed without merging**
